### ISSUE TITLE
Some problem in train_segmented.py

### ISSUE THREAD

**Issue by a0226asdf** [piergiaj/mlb-youtube#10]
I'm recently learning for the pitch type classfication with deep learning , so i try your code on this github.
But there are some error such as : ModuleNotFoundError: No module named 'eccv_models'.

So i search for it and find it might be defined by your own computer thus it can run in you computer but doesn't upload on this github , so i can't to try the experiment myself.

i find there are  same problems in other code ,I think the reason is these objects is stored in your computer but not in the mlb-youtube folder so you didnt upload them on the github.

Apologize for disturbing if i was wrong, can you tell me where can i find those data?

**Comment by piergiaj** [comment]
That import isn't needed here, it was from some other experiments and I forgot to remove it. The file has been updated, removing that dependency.

**Comment by a0226asdf** [comment]
Thanks for the answer
But now I get another error while running train_segmented.py
----------
Traceback (most recent call last):
  File "train_segmented.py", line 164, in <module>
    train_model(model, criterion, optimizer, num_epochs=10)
  File "train_segmented.py", line 94, in train_model
    for data in dataloaders[phase]:
  File "/home/joebaseball10511218/anaconda3/envs/mlb_py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/joebaseball10511218/anaconda3/envs/mlb_py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/joebaseball10511218/anaconda3/envs/mlb_py2/lib/python2.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/joebaseball10511218/mlb-youtube-master1/experiments/segmented_dataset.py", line 70, in __getitem__
    img = np.load(path)
  File "/home/joebaseball10511218/anaconda3/envs/mlb_py2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: u'/GPT7JBQK30ZM.npy'

I found this error caused by the path is wrong, and "GPT7JBQK30ZM" is one of the file name of the segmented video ,however i didn't have any ,npy file 
Does it mean you create the .npy file in other code? because i didn't find you create the .npy file  in train_segmented.py neither in segmented_dataset.py
If so , what is your .npy file look like , does it is per-frame pictues stack in one array with one segmented video ?

If i was wrong could you please tell me where and how you create .npy file , Thanks again

--------------
I've watched preivew issue as #5 and are you use the code in [here](https://github.com/piergiaj/pytorch-i3d/tree/d4852930e5ac4582562ab3ff60ec3847ba85d87f) to extract feature and create .npy file?
