### ISSUE TITLE
Error : run the python extract_continuous_videos.py

### ISSUE THREAD

**Issue by jhj7905** [piergiaj/mlb-youtube#4]
hi @piergiaj 
when i ran the extract_continous_videos.py  then error occured like below
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hyunjo/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/hyunjo/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "extract_continuous_videos.py", line 33, in wrapper
    local_clip(os.path.join(input_directory,filename+'.mkv'), clip['start'], duration, clip['clip_name']+'.mp4', output_directory)
KeyError: 'clip_name'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "extract_continuous_videos.py", line 40, in <module>
    pool.map(wrapper, [data[k] for k in data.keys()])
  File "/home/hyunjo/anaconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/hyunjo/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: 'clip_name'

i downloaded the .mp4 by modifing the download source code
i think it is related to parsing
can you tell me the solution?
thank you in advance

**Comment by piergiaj** [comment]
I changed the format of the dataset and forgot to update the download scripts.

Simply add this before pool.map (roughly line 40), and it will work correctly.

I'll correct and update the code shortly.

```
for k in data.keys():
    data[k]['clip_name'] = k
```

**Comment by jhj7905** [comment]
@piergiaj 

Thank you!

with open('data/mlb-youtube-segmented.json', 'r') as f:
    data = json.load(f)
    pool = multiprocessing.Pool(processes=8)
    for k in data.keys():
        data[k]['clip_name'] = k
    pool.map(wrapper, [data[k] for k in data.keys()])
